# Generated by Django 4.0.4 on 2022-05-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gechtech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requirements', models.FileField(upload_to='media')),
                ('price', models.CharField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
