# Generated by Django 4.0.4 on 2022-05-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gechtech', '0002_orders_delete_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
