# Generated by Django 4.0.4 on 2022-05-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gechtech', '0003_orders_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
