# Generated by Django 4.0.4 on 2022-05-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gechtech', '0004_rename_orders_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='requirements',
            field=models.FileField(upload_to=''),
        ),
    ]
