# Generated by Django 3.1.14 on 2022-05-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gechtech', '0005_alter_order_price_alter_order_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('deadline', models.DateTimeField()),
                ('file', models.FileField(upload_to='')),
                ('pages', models.IntegerField()),
            ],
        ),
    ]
