# Generated by Django 3.1.14 on 2022-05-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gechtech', '0006_clientorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
