# Generated by Django 3.1.14 on 2022-05-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gechtech', '0007_auto_20220519_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='file',
            field=models.FileField(upload_to='media'),
        ),
    ]
