# Generated by Django 3.1.14 on 2022-05-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gechtech', '0009_supportticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
