# Generated by Django 3.1.14 on 2022-05-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gechtech', '0010_auto_20220519_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
    ]
