# Generated by Django 3.1.5 on 2022-09-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gechtech', '0011_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Get',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('requirements', models.FileField(upload_to='media')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
